In [1]:
from concurrent.futures import ThreadPoolExecutor, ProcessPoolExecutor, Future

In [2]:
MAX_WORKERS = 4

thread_executor = ThreadPoolExecutor(max_workers=MAX_WORKERS)
process_executor = ProcessPoolExecutor(max_workers=MAX_WORKERS)

In [3]:
def do_some_math(x: float) -> float:
    return x * x

In [4]:
result = thread_executor.submit(do_some_math, 5)

In [5]:
import math

result = process_executor.submit(math.sqrt, 5)

In [6]:
result

<Future at 0x107028a40 state=finished returned float>

In [7]:
result.result()

2.23606797749979

In [6]:
results = thread_executor.map(do_some_math, range(10))

In [7]:
results

<generator object Executor.map.<locals>.result_iterator at 0x10594c310>

In [8]:
next(results)

0

In [9]:
thread_executor.submit(lambda x: x * x, 5).result()

25

In [10]:
process_executor.submit(lambda x: x * x, 5).result()

PicklingError: Can't pickle <function <lambda> at 0x105926ac0>: attribute lookup <lambda> on __main__ failed

In [17]:
print(results)

<generator object Executor.map.<locals>.result_iterator at 0x122f8fc40>


In [18]:
executor = thread_executor

In [41]:
import time
import random

def do_some_math(x: float) -> float:
    time.sleep(random.random())
    # if x < 0.5:
    #     raise ValueError('x is too small')
    return x

In [42]:
from concurrent.futures import as_completed, wait
from functools import partial

In [43]:
futures = map(partial(executor.submit, do_some_math), range(10))

In [39]:
for future in as_completed(futures):
    print(future.result())

3
4
1
2


ValueError: x is too small

In [47]:
from concurrent.futures import wait, FIRST_COMPLETED, FIRST_EXCEPTION, ALL_COMPLETED

futures = map(partial(executor.submit, do_some_math), range(10))

completed, not_completed = wait(futures, timeout=1, return_when=FIRST_COMPLETED)

In [48]:
completed

{<Future at 0x122b878f0 state=finished returned int>}

In [49]:
not_completed

{<Future at 0x122b38b60 state=finished returned int>,
 <Future at 0x122b38c50 state=finished returned int>,
 <Future at 0x122b38cb0 state=finished returned int>,
 <Future at 0x122b39c70 state=finished returned int>,
 <Future at 0x122b3b230 state=finished returned int>,
 <Future at 0x122b3b980 state=finished returned int>,
 <Future at 0x122b3bef0 state=finished returned int>,
 <Future at 0x122b84380 state=finished returned int>,
 <Future at 0x122b87c20 state=finished returned int>}

In [9]:
import asyncio

In [10]:
await asyncio.sleep(1)

In [11]:
future = process_executor.submit(math.sqrt, 5)
aio_future = asyncio.wrap_future(future)
aio_future

<Future pending cb=[_chain_future.<locals>._call_check_cancel() at /Users/kuba/mambaforge/envs/europython-24/lib/python3.12/asyncio/futures.py:387]>

In [12]:
aio_result = await aio_future

In [13]:
aio_result

2.23606797749979

In [1]:
import loky

In [2]:
executor = loky.get_reusable_executor(max_workers=4, timeout=2)

In [7]:
executor.submit(lambda x: x + 1, 5).result()

6

In [10]:
3000/45

66.66666666666667

In [11]:
3 / (3/4)

4.0

In [12]:
11500 / 5

2300.0

In [40]:
import numpy as np
np.random.seed(42)
# list(process_executor.map(np.random.randint, 8*[100]))

In [50]:
np.random.randint(100)

71

In [51]:
list(process_executor.map(np.random.randint, 8*[100]))

[60, 60, 60, 60, 60, 60, 60, 60]

In [9]:
list(process_executor.map(np.random.rand, 4*[1]))

[array([0.78564155]),
 array([0.78564155]),
 array([0.78564155]),
 array([0.78564155])]

In [12]:
list(process_executor.map(np.random.sample, 4*[((1, ))]))

[array([0.73608751]),
 array([0.0961075]),
 array([0.00821157]),
 array([0.47264525])]

In [3]:
import calculations

In [4]:
df = process_executor.submit(calculations.load_data)
df

<Future at 0x12abaaf00 state=running>

In [5]:
future = process_executor.submit(calculations.a_mean, df)

In [6]:
future.result()

TypeError: cannot pickle '_thread.RLock' object